### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by ZIM555** [SandPox/android_external_chromium-webview#1]
03-12 19:19:03.367 E/chromium(3741): [ERROR:gles2_cmd_decoder.cc(11333)] [GroupMarkerNotSet(crbug.com/242999)!:9CA53A5E]GL ERROR :GL_INVALID_OPERATION : glConsumeTextureCHROMIUM: invalid mailbox name
03-12 19:19:03.368 E/chromium(3741): [ERROR:gles2_cmd_decoder.cc(6430)] [GroupMarkerNotSet(crbug.com/242999)!:9CA53A5E]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

Try build with this flag

--disable-layer-squashing
--disable-repaint-after-layout
--disable-accelerated-overflow-scroll

**Comment by SandPox** [comment]
I know, there is something else caused this broken, I'm compiling with your given flag

**Comment by SandPox** [comment]
Solved!
